// Mock data for Z Fellows applications
const mockCandidates = [
    {
        id: 1,
        email: "alanjech@gmail.com",
        firstName: "Alan",
        lastName: "Chen",
        company: "Gradient",
        aiScore: 95,
        birthday: "2003-05-12",
        phone: "4155551234",
        technical: "Yes",
        previouslyApplied: "No",
        location: "San Francisco, CA",
        schoolOrWork: "UT Austin Turing Scholar (CS Honors)",
        projectDescription: "Building Gradient, a personalized Olympiad AI mentor. 80 students reached finals (Top 4 in US). Taught 2400+ students across 5 years. Backed by angels, pitching academics like X-Camp.",
        problemSolving: "Top students need personalized, expert-level coaching. Private tutors cost $200+/hr. Generic online courses don't adapt to individual learning styles.",
        expertise: "Taught 2400+ students over 5 years. Built full prototype with 80 paying users. NLP research at UT Austin. Deep competitive math/science background.",
        competitors: "Art of Problem Solving and Olympiad prep are one-size-fits-all. I provide adaptive, real-time feedback on specific weaknesses via AI-analyzed problem-solving approaches.",
        pastWork: "Led 4 student orgs (100+ members). Built AI tutoring system (80 national qualifiers). NLP research at UT Austin. Taught 2400+ students.",
        nerdy: "Reverse-engineered a dating app's API to see who liked me without paying.",
        drives: "Democratizing world-class education. Talented students shouldn't be held back by lack of resources.",
        nonTraditional: "Started teaching competitive math/science at 14. Built network of 2400+ students before graduating high school. Competed nationally in multiple Olympiads.",
        riskOrChallenge: "Scraped school email server, cold emailed 70K people for users. Almost expelled with 1 semester left. On visa, so expulsion = visa revocation. Shows willingness to break norms for success.",
        website: "https://gradient.ai, https://linkedin.com/in/alanchen",
        achievements: "Top 4 US Physics Olympiad, USACO Gold, 2400+ students taught, 80 paying users month 1, UT Austin NLP research",
        videoLink: "https://youtube.com/watch?v=example1",
        cofounder: "Jessica Liu - MIT engineer, built recommendation engine at Series B startup",
        howHeard: "Twitter / X",
        helpNeeded: "Need technical cofounder intros - smart people passionate about education."
    },
    {
        id: 2,
        email: "lisany@stanford.edu",
        firstName: "Lisany",
        lastName: "Daniel Lin",
        company: "Inkwise",
        aiScore: 92,
        birthday: "2002-09-23",
        phone: "6502349876",
        technical: "Yes",
        previouslyApplied: "Yes",
        location: "Palo Alto, CA",
        schoolOrWork: "Stanford CS, ex-OpenAI intern",
        projectDescription: "AI reading tool for dyslexic students. Computer vision tracks eye movements, adapts text in real-time. 50 students piloted: 40% improvement in reading speed/comprehension.",
        problemSolving: "15% of students have dyslexia. Most tools are static, don't adapt. Students struggle, fall behind.",
        expertise: "Have dyslexia myself. Stanford CV and accessibility research. OpenAI multimodal models intern. Full prototype built, piloted with 50 students at 3 schools.",
        competitors: "Grammarly/Read&Write are generic overlays. Dyslexia manifests differently per person. My AI personalizes spacing, font, color, pacing via real-time eye tracking.",
        pastWork: "OpenAI multimodal intern. Published at Stanford HCI. Browser extension (10K+ users). Taught coding to students with learning disabilities.",
        nerdy: "Built custom mechanical keyboard with different key heights optimized for my typing patterns (6 months keystroke data).",
        drives: "Making tech accessible. Struggled with dyslexia growing up. No student should fall behind due to poor tool design.",
        nonTraditional: "Got district-wide dyslexia policy changes at my high school. Started nonprofit providing free assistive tech to low-income students.",
        riskOrChallenge: "Cold-called 50 principals, rejected 47 times before 3 yes's. Terrifying but needed real feedback. Those 3 pilots proved the concept.",
        website: "https://inkwise.io, https://github.com/lisanylin",
        achievements: "CHI 2024 publication, OpenAI intern, 10K+ users prior project, 3 school pilots (50 students), 40% reading improvement",
        videoLink: "https://youtube.com/watch?v=example2",
        cofounder: "Dr. Sarah Chen - UCSF dyslexia researcher, 15 years studying reading interventions",
        howHeard: "Previous Z Fellows cohort member",
        helpNeeded: "School district procurement help. Intros to K-12 SaaS sellers."
    },
    {
        id: 3,
        email: "josh.le@nyu.edu",
        firstName: "Josh",
        lastName: "Le",
        company: "LocalLoop",
        aiScore: 78,
        birthday: "2001-03-15",
        phone: "2125556789",
        technical: "No",
        previouslyApplied: "No",
        location: "Brooklyn, NY",
        schoolOrWork: "NYU Stern, part-time at VC fund",
        projectDescription: "Platform connecting local businesses with micro-influencers (1K-10K followers). 20% commission. $15K revenue in 2 months, 40 businesses, 200 influencers in Brooklyn.",
        problemSolving: "Local businesses can't afford influencer marketing ($500-5K/post) but need social presence. Micro-influencers too small for AspireIQ.",
        expertise: "Grew Instagram to 50K, made $30K from brand deals. Understand both sides. VC fund: sourced 5 deals. Signed 40 businesses, 200 influencers in 3 months.",
        competitors: "AspireIQ/Grin focus on big brands and macro-influencers. Local businesses need hyper-local, affordable marketing. My unit economics: $50-200/campaign vs $5K+.",
        pastWork: "50K Instagram followers, $30K brand deals. Sourced 5 VC deals. Ran social for 3 businesses (30% revenue growth avg). Shopify app (500+ installs).",
        nerdy: "4-year spreadsheet tracking every Instagram post: engagement, time, caption length, hashtags for content optimization.",
        drives: "Help small businesses compete with chains. Parents' restaurant struggled with marketing. Want to give every local business tools to thrive.",
        nonTraditional: "Paid Instagram promotions at 16 to pay for college. Built network of 200+ NYC business owners via cold outreach.",
        riskOrChallenge: "Dropped VC internship for LocalLoop full-time, gave up $100K return offer. Parents furious (first-gen). Had PMF, needed speed. Now $15K MRR, 40% MoM growth.",
        website: "https://localloop.io, https://instagram.com/joshle",
        achievements: "$15K revenue (2 months), 40 businesses + 200 influencers, 50K Instagram followers, $30K brand deals, Brooklyn Magazine feature",
        videoLink: "",
        cofounder: "Marcus Johnson - growth marketer, scaled D2C 0→$5M in 18 months",
        howHeard: "LinkedIn post from Z Fellows alum",
        helpNeeded: "Marketplace dynamics help - balancing supply/demand scaling to new cities."
    },
    {
        id: 4,
        email: "azaria@gmail.com",
        firstName: "Azaria",
        lastName: "Kelman",
        company: "ChartAhead",
        aiScore: 99,
        birthday: "2003-01-08",
        phone: "6475455406",
        technical: "Yes",
        previouslyApplied: "No",
        location: "Toronto",
        schoolOrWork: "UofT, KPMG intern",
        projectDescription: "Intake-to-charting tool turning patient responses into physician-ready SOAP notes. Integrates into existing workflows, cuts documentation time. Doctors spend hours on paperwork - huge impact on care quality and burnout.",
        problemSolving: "Physicians spend 1-2 hrs daily writing charts, miss details, copy-paste old notes. Existing tools slow, generic, require big workflow changes. ChartAhead: accurate structured charts from patient input.",
        expertise: "Built full prototype (Vite/React, Supabase, Gemini). Shipped multiple production apps including open-source AI tutoring system. Work with Dr. Barry Pakes (prominent physician) to validate workflows.",
        competitors: "Competitors do live scribing or full AI EHR replacements - heavy, expensive, disruptive. I focus on one wedge: patient intake → charts. Shorter adoption, 10× improvement, no workflow disruption.",
        pastWork: "TutorFlowAI (audio, LLMs, collaborative whiteboard). WikiSurfer (curated Wikipedia). Multiple production React apps. Open-source contributor. Led IT for 600-camper summer program.",
        nerdy: "Downloaded Instagram data to figure out who added me first vs who I added first.",
        drives: "Taking painful workflows and removing the pain completely with software.",
        nonTraditional: "Led IT ops for 600-camper program at 17. Shipped multiple production apps before university. Self-taught programmer since 14.",
        riskOrChallenge: "Cold-emailed 30 physicians, ignored by 28. 2 responses gave brutal feedback (prototype unusable). Spent 3 weeks rebuilding. Now one is paying customer and advisor.",
        website: "https://chartahead.io, https://github.com/azariakelman",
        achievements: "TutorFlowAI (200+ GitHub stars), 5+ production apps, working with Dr. Barry Pakes (prominent ER doc), KPMG intern",
        videoLink: "",
        cofounder: "Emma Zhang - product designer at health-tech unicorn, deep clinical workflow understanding",
        howHeard: "Twitter / X",
        helpNeeded: "Healthcare compliance (HIPAA) and hospital system sales. Intros to healthcare org sellers."
    },
    {
        id: 5,
        email: "maria.santos@mit.edu",
        firstName: "Maria",
        lastName: "Santos",
        company: "CodeMentor",
        aiScore: 85,
        birthday: "2002-11-30",
        phone: "6175552345",
        technical: "Yes",
        previouslyApplied: "No",
        location: "Cambridge, MA",
        schoolOrWork: "MIT CS, ex-Google intern",
        projectDescription: "AI pair programmer trained on beginner mistakes. Unlike Copilot, explains why code works, catches beginner errors, teaches best practices. Piloting with 200 students at MIT + 2 community colleges.",
        problemSolving: "Beginners make same mistakes repeatedly, don't understand failures. Office hours limited, StackOverflow intimidating. Need 24/7 patient tutor.",
        expertise: "TAed 3 MIT intro CS courses (500+ students). Google developer tools intern. Built prototype using fine-tuned LLMs on 10K+ beginner errors from office hours.",
        competitors: "Copilot/ChatGPT are general-purpose, don't understand pedagogy. Give answers, not teaching. Beginners need explanations. My AI uses Socratic questions, guides to answers.",
        pastWork: "TAed 3 MIT courses. Google developer tools intern. VS Code extension (5K+ installs). Tutored 50+ students privately.",
        nerdy: "Collection of 10K+ beginner programming errors categorized by type, frequency, debug difficulty. Use to train AI models.",
        drives: "Democratizing CS education. First in family to code. Make it accessible to everyone, not just CS backgrounds.",
        nonTraditional: "Self-taught at 12 using library computers (family couldn't afford one). Started free coding bootcamp in hometown (100+ students taught).",
        riskOrChallenge: "Built 6 months before showing anyone (afraid of criticism). Professor said 'too hand-holdy.' Almost quit. Pilot with 20 students: 25% test score improvement. Trust your vision when experts disagree.",
        website: "https://codementor.ai, https://github.com/mariasantos",
        achievements: "TAed 3 MIT courses, Google intern, 5K+ VS Code installs, 200 student pilot (25% score improvement), 100+ bootcamp students taught",
        videoLink: "https://youtube.com/watch?v=example5",
        cofounder: "Prof. David Miller - MIT CS, taught intro programming 20 years, deep pedagogy understanding",
        howHeard: "MIT startup fair",
        helpNeeded: "University GTM strategy. Intros to higher ed SaaS sellers."
    },
    {
        id: 6,
        email: "raj.patel@berkeley.edu",
        firstName: "Raj",
        lastName: "Patel",
        company: "FreshRoute",
        aiScore: 82,
        birthday: "2001-07-19",
        phone: "5105558765",
        technical: "No",
        previouslyApplied: "Yes",
        location: "Oakland, CA",
        schoolOrWork: "UC Berkeley Econ, family restaurant",
        projectDescription: "Logistics platform for small farms → restaurants. Aggregate orders, optimize routes, handle payments. Farmers get 30% higher margins, restaurants get fresher produce cheaper. $25K GMV month 1, 8 farms, 15 restaurants (Bay Area).",
        problemSolving: "Small farms can't afford individual restaurant delivery (expensive, time-consuming). Restaurants want local produce but distributors mark up 50%+, produce sits for days.",
        expertise: "Family runs restaurant - saw produce pain firsthand. 2 months visiting farms/restaurants understanding pain points. Built full platform, signed 8 farms, 15 restaurants. Deep restaurant ops and supply chain knowledge.",
        competitors: "Sysco/US Foods slow and expensive. GrubMarket focuses on consumers, not B2B. Restaurants need consistent supply, competitive pricing, next-day delivery. My unit economics work via demand aggregation.",
        pastWork: "Managed family restaurant ops 3 years. Food delivery app (1K+ users). Logistics startup intern (route optimization). Consulted 5 restaurants on cost reduction.",
        nerdy: "Spreadsheet model calculating optimal routes for 50 stops considering traffic, delivery windows, vehicle capacity. Use for every FreshRoute delivery.",
        drives: "Supporting small farms and local food. Industrial ag destroying planet, small farms dying. Make local food economically viable.",
        nonTraditional: "Worked family restaurant since 10. Managing inventory and negotiating suppliers by 16. Learned business by doing, not textbooks.",
        riskOrChallenge: "Invested $10K savings for used van to launch. Parents thought I was crazy (college fund risk). Month 1: van broke 3x, lost $3K. Fixed it myself (YouTube). Now profitable. Bet on yourself.",
        website: "https://freshroute.io",
        achievements: "$25K GMV month 1, 8 farms + 15 restaurants, profitable month 2, 20% avg restaurant cost reduction, 3 farms +40% revenue",
        videoLink: "https://youtube.com/watch?v=example6",
        cofounder: "Lisa Chen - Amazon Logistics supply chain expert, route optimization and inventory mgmt",
        howHeard: "YC Startup School",
        helpNeeded: "Scaling to new cities. Intros to marketplace founders who expanded geographically."
    },
    {
        id: 7,
        email: "sarah.kim@yale.edu",
        firstName: "Sarah",
        lastName: "Kim",
        company: "HealthBridge",
        aiScore: 91,
        birthday: "2002-04-22",
        phone: "2035557890",
        technical: "Yes",
        previouslyApplied: "No",
        location: "New Haven, CT",
        schoolOrWork: "Yale CS, ex-Stripe intern",
        projectDescription: "Building HealthBridge, connecting patients in underserved areas with telehealth specialists. AI-powered triage routes to right specialist. 500 patients served, 15 clinics in 3 states. $8K MRR.",
        problemSolving: "Rural areas lack specialist access. Patients drive 2+ hours or skip care. Telehealth exists but no smart routing. HealthBridge matches patients to specialists instantly.",
        expertise: "Built full platform (React, Node, Twilio). Stripe payments intern. Partnered with 15 clinics. Father is rural doctor - saw problem firsthand.",
        competitors: "Teladoc/Amwell are generic, no smart routing. I use AI to analyze symptoms and match optimal specialist, reducing wait times 80%.",
        pastWork: "Stripe payments intern. Built clinic management system (200+ users). Volunteered at rural health clinics. Published healthcare AI research.",
        nerdy: "Built a Chrome extension that analyzes medical research papers and summarizes key findings using NLP. 2K+ doctor users.",
        drives: "Healthcare equity. Grew up in rural area where nearest specialist was 3 hours away. Everyone deserves quality care regardless of location.",
        nonTraditional: "Translated for non-English speaking patients at free clinic since 15. Saw healthcare gaps firsthand. Started coding to solve it.",
        riskOrChallenge: "Cold-called 50 rural clinics to pilot HealthBridge. 48 rejections. 2 yes's gave me initial traction. Now those clinics refer others. Persistence pays.",
        website: "https://healthbridge.io, https://github.com/sarahkim",
        achievements: "Stripe intern, 500 patients served, $8K MRR, 15 clinic partnerships, Yale healthcare AI research, 2K+ users on medical research tool",
        videoLink: "",
        cofounder: "Dr. James Chen - telemedicine pioneer, built telehealth platform acquired for $50M",
        howHeard: "Twitter / X",
        helpNeeded: "Navigating healthcare regulations (HIPAA, state licensing). Intros to healthcare compliance experts."
    },
    {
        id: 8,
        email: "marcus.johnson@gmail.com",
        firstName: "Marcus",
        lastName: "Johnson",
        company: "SkillSwap",
        aiScore: 76,
        birthday: "2001-08-14",
        phone: "4045558901",
        technical: "No",
        previouslyApplied: "No",
        location: "Atlanta, GA",
        schoolOrWork: "Georgia Tech dropout, full-time on SkillSwap",
        projectDescription: "Peer-to-peer skill exchange platform. Trade skills instead of paying cash. Guitar lessons for coding help. 5K users, 2K exchanges completed. $3K MRR from premium features.",
        problemSolving: "People want to learn new skills but can't afford classes. Experts want to learn too but don't want to teach for free. SkillSwap enables barter.",
        expertise: "Grew community to 5K users in 6 months. Ran marketing at 2 startups. Built SkillSwap with no-code tools. Strong community building and growth skills.",
        competitors: "Skillshare/Udemy are paid courses, not peer-to-peer. I enable direct skill exchange, building real relationships and accountability.",
        pastWork: "Marketing at 2 startups (grew one from 0 to 10K users). Built 3 online communities (20K+ total members). Self-taught growth hacker.",
        nerdy: "Created a spreadsheet tracking every growth experiment I've run (200+) with conversion rates, costs, and learnings. Use it to optimize everything.",
        drives: "Democratizing education. Dropped out because college was too expensive. Want everyone to access learning regardless of money.",
        nonTraditional: "Dropped out sophomore year to work full-time. Parents were furious. Proved them wrong by building profitable business.",
        riskOrChallenge: "Invested last $5K into Facebook ads for SkillSwap. Ads flopped, lost everything. Switched to organic community building. Now growing 40% MoM with $0 ad spend.",
        website: "https://skillswap.io, https://twitter.com/marcusjohnson",
        achievements: "5K users, 2K exchanges, $3K MRR, grew startup to 10K users, built 20K+ member communities, 40% MoM growth",
        videoLink: "",
        cofounder: "Alex Rivera - engineer who scaled marketplace at Airbnb, understands two-sided platforms",
        howHeard: "LinkedIn post from Z Fellows alum",
        helpNeeded: "Marketplace dynamics - balancing supply/demand. Intros to marketplace founders."
    },
    {
        id: 9,
        email: "priya.sharma@princeton.edu",
        firstName: "Priya",
        lastName: "Sharma",
        company: "VoiceAI",
        aiScore: 89,
        birthday: "2003-02-11",
        phone: "6095559012",
        technical: "Yes",
        previouslyApplied: "Yes",
        location: "Princeton, NJ",
        schoolOrWork: "Princeton CS, ML research lab",
        projectDescription: "Real-time voice translation for customer service. AI translates calls instantly, no language barriers. Piloting with 3 call centers (500+ agents). 95% translation accuracy.",
        problemSolving: "Call centers lose customers due to language barriers. Human translators expensive and slow. VoiceAI translates in real-time with natural voice.",
        expertise: "ML research at Princeton (speech recognition). Built full prototype (Python, TensorFlow, WebRTC). Published 2 papers on voice AI. Fluent in 4 languages.",
        competitors: "Google Translate is text-based, not real-time voice. I built for call center use case: handles accents, background noise, industry jargon.",
        pastWork: "Princeton ML research (2 publications). Built voice assistant for elderly (1K users). Interned at Amazon Alexa team. Contributed to open-source speech models.",
        nerdy: "Trained custom speech model on 10K hours of call center audio I collected. Model handles 15 languages and call center-specific terminology.",
        drives: "Breaking language barriers. Immigrant parents struggled with English. Saw them miss opportunities due to language. Want to eliminate that barrier.",
        nonTraditional: "Taught myself ML at 14 using free online courses. Published first paper at 17. Started company before graduating.",
        riskOrChallenge: "Spent 8 months building perfect tech before talking to customers. First demo: call center said 'too complex.' Rebuilt entire UX in 2 weeks based on feedback. Now they love it.",
        website: "https://voiceai.io, https://github.com/priyasharma",
        achievements: "2 ML publications, 3 call center pilots (500+ agents), 95% accuracy, Amazon Alexa intern, 1K users on previous project",
        videoLink: "https://youtube.com/watch?v=example9",
        cofounder: "Dr. Lisa Wang - Stanford linguistics professor, expert in multilingual communication",
        howHeard: "Princeton startup fair",
        helpNeeded: "Enterprise sales to call centers. Intros to call center decision makers."
    },
    {
        id: 10,
        email: "tyler.brown@gmail.com",
        firstName: "Tyler",
        lastName: "Brown",
        company: "FarmDirect",
        aiScore: 73,
        birthday: "2000-12-05",
        phone: "5155553456",
        technical: "No",
        previouslyApplied: "No",
        location: "Des Moines, IA",
        schoolOrWork: "Iowa State Ag Business, family farm",
        projectDescription: "E-commerce platform for small farms to sell directly to consumers. Handles logistics, payments, delivery. 25 farms, 1K customers, $40K GMV/month.",
        problemSolving: "Small farms can't compete with industrial ag. Middlemen take 50%+ margins. Consumers want local food but it's hard to find. FarmDirect connects both.",
        expertise: "Grew up on family farm. Understand farm economics deeply. Built platform with Shopify + custom logistics. Signed 25 farms in 4 months.",
        competitors: "Farmers markets are limited hours/locations. CSA boxes are inflexible. I offer on-demand ordering with next-day delivery.",
        pastWork: "Managed family farm operations (200 acres). Built e-commerce site for farm ($100K revenue). Consulted 10 farms on direct-to-consumer sales.",
        nerdy: "Optimized delivery routes using custom algorithm considering farm locations, customer addresses, and product freshness. Cut delivery costs 40%.",
        drives: "Saving family farms. Watched neighbors lose farms to industrial ag. Want to make small farming economically viable again.",
        nonTraditional: "Worked on farm since age 8. Learned business by managing farm operations. College was secondary to real-world experience.",
        riskOrChallenge: "First delivery day: truck broke down with $5K of produce. Rented U-Haul, delivered everything myself, 18-hour day. Lost money but kept customers happy. Now have backup plans.",
        website: "https://farmdirect.io",
        achievements: "$40K GMV/month, 25 farms, 1K customers, $100K revenue on family farm site, 40% delivery cost reduction",
        videoLink: "",
        cofounder: "Emily Chen - supply chain expert from Instacart, understands fresh food logistics",
        howHeard: "YC Startup School",
        helpNeeded: "Scaling logistics to new regions. Intros to logistics/supply chain experts."
    },
    {
        id: 11,
        email: "nina.patel@columbia.edu",
        firstName: "Nina",
        lastName: "Patel",
        company: "MindfulAI",
        aiScore: 86,
        birthday: "2002-06-18",
        phone: "2125554567",
        technical: "Yes",
        previouslyApplied: "No",
        location: "New York, NY",
        schoolOrWork: "Columbia CS + Psychology, mental health research",
        projectDescription: "AI mental health companion for college students. 24/7 support, detects crisis signals, connects to counselors. 2K students at 5 universities. 85% report improved mental health.",
        problemSolving: "College counseling centers overwhelmed. 6-week wait times. Students in crisis have nowhere to turn. MindfulAI provides immediate support and triage.",
        expertise: "Built full app (React Native, GPT-4, crisis detection ML). Psychology research on mental health interventions. Partnered with 5 university counseling centers.",
        competitors: "BetterHelp/Talkspace are expensive ($260+/month). Replika is entertainment, not clinical. I'm affordable ($20/month), evidence-based, integrated with campus resources.",
        pastWork: "Mental health research at Columbia (2 studies). Built meditation app (5K users). Peer counselor training. Volunteered at crisis hotline.",
        nerdy: "Fine-tuned LLM on 50K therapy transcripts (anonymized) to recognize crisis language patterns. Model flags concerning messages for human review.",
        drives: "Mental health accessibility. Lost friend to suicide sophomore year. Campus counseling was booked for weeks. No one should wait for help.",
        nonTraditional: "Started peer counseling at 16 after personal mental health struggles. Turned pain into purpose by helping others.",
        riskOrChallenge: "First user sent suicidal message. My AI flagged it, I called campus police, they intervened. Terrifying but proved the system works. Now have 24/7 crisis protocol.",
        website: "https://mindfulai.app, https://github.com/ninapatel",
        achievements: "2K users at 5 universities, 85% improved mental health, 2 psychology studies, 5K users on meditation app, crisis detection system",
        videoLink: "https://youtube.com/watch?v=example11",
        cofounder: "Dr. Michael Lee - clinical psychologist, 20 years treating college students, understands campus mental health",
        howHeard: "Columbia startup competition",
        helpNeeded: "Mental health regulations and liability. Intros to healthcare lawyers and mental health tech founders."
    }
];

